services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-bitcoin}
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-pass}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    restart: unless-stopped

  redpanda:
    image: redpandadata/redpanda:v24.1.9
    container_name: redpanda
    command: >
      redpanda start
      --overprovisioned
      --smp 1
      --memory 512M
      --reserve-memory 0M
      --node-id 0
      --check=false
      --kafka-addr PLAINTEXT://0.0.0.0:9092
      --advertise-kafka-addr PLAINTEXT://redpanda:9092
    ports:
      - "9092:9092"
      - "9644:9644"
    restart: unless-stopped

  producer:
    build: ./producer
    environment:
      KAFKA_BROKER: ${KAFKA_BROKER:-redpanda:9092}
      KAFKA_TOPIC: ${KAFKA_TOPIC:-bitcoin}
    volumes:
      - ./data:/app/data:ro
    # ENTRYPOINT in Dockerfile ist schon ["python","producer.py"].
    # Deshalb hier NUR der CSV-Pfad als command:
    command: ["/app/data/bitcoin_sample.csv"]
    depends_on:
      - redpanda

  spark:
    image: bitnami/spark:3.5
    volumes:
      - ./spark:/opt/spark-apps
      - ./data:/app/data:ro
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-bitcoin}
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-pass}
      POSTGRES_HOST: postgres
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      KAFKA_BROKER: ${KAFKA_BROKER:-redpanda:9092}
      KAFKA_TOPIC: ${KAFKA_TOPIC:-bitcoin}
      SPARK_APP_NAME: ${SPARK_APP_NAME:-BitcoinETL}
      # Wichtig: PySpark-Interpreter im Bitnami-Image:
      PYSPARK_PYTHON: /opt/bitnami/python/bin/python3
      PYSPARK_DRIVER_PYTHON: /opt/bitnami/python/bin/python3
    depends_on:
      - postgres
      - redpanda
    command: >
      bash -lc "/opt/bitnami/spark/bin/spark-submit
      --conf spark.pyspark.python=/opt/bitnami/python/bin/python3
      --conf spark.pyspark.driver.python=/opt/bitnami/python/bin/python3
      --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.0,org.postgresql:postgresql:42.7.3
      /opt/spark-apps/spark_job.py"

